### Creates a new task and publishes it to the Redis server
POST http://localhost:5001/create
Content-Type: application/json

{
  "name": "task one",
  "status":"pending"
}


### get all tasks
GET http://localhost:5001/data

### delete task by given id
DELETE http://localhost:5001/delete/5