### create a new task
POST http://localhost:5001/create
Content-Type: application/json

{
  "name": "task four",
  "status":"pending"
}

###

GET http://localhost:5001/

### test connection
GET http://localhost:5001/data